### PR TITLE
feat: email theme

### LINKED ISSUE #47: E-Mail Theme
Hey volks,
are there plans to introduce an keycloak tailwind / mailwind email theme?

### PR DESCRIPTION
**Pull request by paulwer**
closes https://github.com/lukin/keywind/issues/47
references https://github.com/lukin/keywind/issues/6

Hey folks, ive managed a [mailwind](https://www.mailwind.io/) integration. 

From my pov it may not be perfect, but it works as intended (for me).
any thoughts on this?

I've created this theme based on the mailwind front-website example.

emails should be tested for visibility on the most used e-mail clients (help wanted):

- [x] Apple
- [X] GMAIL
- [x] Outlook 
- [x] Thunderbird
- [x] Yahoo Mail
- [x] WEB.de
- [x] Outlook.com

### CODE REVIEW

**Comment by paulwer** [comment]
did someone want to check/help and give feedback for a client?
@CHE1RON @lukin

**Comment by paulwer** [comment]
**display on gmail**
Unbekannt

known issues:
- fallback to background color, because background div is not displayed properly

**Comment by CHE1RON** [comment]
Looks promising! Never heard of Mailwind before, thanks!

**Comment by paulwer** [comment]
display on web.de
Unbenannt
known issues:
- fallback to background color -> reason: not checked

**Comment by paulwer** [comment]
@CHE1RON @lukin any other providers needed / wished / to be checked?

**Comment by CHE1RON** [comment]
I guess Gmail as de-facto standard is all that needs to be checked really 😅

**Comment by CHE1RON** [comment]
Don't get me wrong, privately I don't have a Gmail account - but nearly everyone I know has one ..

**Comment by paulwer** [comment]
outlook still doesnt looks great, i guess exspecialy for companies, this would be great to optimize at least -_-

**Comment by CHE1RON** [comment]
As far as my scarce experience with Outlook goes, fixing it is out of scope for `keywind` 😂

**Comment by paulwer** [comment]
i think checking on apple should be also a prio:
1689235958-most-used-email-clients-worldwide

**Comment by CHE1RON** [comment]
Feel free to send emails to folkers [at] codefy [dot] de and I'll post screenshots 😉

**Comment by paulwer** [comment]
@CHE1RON you should have recieved an email yesterday :)

**Comment by CHE1RON** [comment]
Screenshot 2023-09-29 at 10 03 23

looks good 👍

**Comment by paulwer** [comment]
yahoo
Unbenannt

known issues:
- no background at all => I guess we can ignore this

**Comment by paulwer** [comment]
as mentioned outlook still looks not good, i will try to come up with some changes to change this:
Unbenannt

**Comment by CHE1RON** [comment]
@paulwer I mean it says right there in your screenshot: if it looks shitty, please view it in your browser 😂

**Comment by paulwer** [comment]
I've sended you another e-mail, please check the formatting, outlook looks now better and the other platforms are still optical the same:
Unbenannt

**Comment by paulwer** [comment]
outlook.com works like a charm <3
Unbenannt

**Comment by paulwer** [comment]
thunderbird also works great <3
Unbenannt

**Comment by paulwer** [comment]
@lukin any test files needed for this PR?

**Comment by CHE1RON** [comment]
macOS Mail, as requested:

image

**Comment by CHE1RON** [comment]
macOS Mail:

image

**Comment by paulwer** [comment]
@lukin this pr is ready to be merged

**Comment by paulwer** [comment]
within this commit, I used the mailwind logo as default logo.
should we replace it with a keycloak logo to match a more "default" - alike look or remove the logo by default, to be fit with plain installation and maybe display just the realm name, if nothing is defined...
I could also imagine a customization behavior within theme.properties, like mentioned in: #59 

any opinions on that? @lukin @CHE1RON

**Comment by CHE1RON** [comment]
I see no apparent reason why `keywind` should propagate `Mailwind` by using its logo by default 🤔 

No logo imho 👍

**Comment by paulwer** [comment]
@CHE1RON is right, the logo should be optional. Therefore i will push a commit with the mentioned themeLogoUrl as property of the theme shortly.

**Comment by paulwer** [comment]
closed in favor for:
https://github.com/lukin/keywind/pull/96

**Comment by LeftoversTodayAppAdmin** [comment]
Hey folks, 
How do I get the email template? The latest keywind branch still doesnt show any email templates at all?

**Comment by paulwer** [comment]
this was closed in favor for #96.
all changes here are present in the other pr

**Pull request closed without merging**
